"""Add role to the new user

Revision ID: 51b0bdaa8422
Revises: 4b1a3b10e4ab
Create Date: 2025-12-25 19:06:48.765039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51b0bdaa8422'
down_revision: Union[str, Sequence[str], None] = '4b1a3b10e4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.VARCHAR(length=50), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
