"""add relationship

Revision ID: 7c9352d22c16
Revises: c2cb1027c58a
Create Date: 2026-02-01 16:08:22.433955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c9352d22c16'
down_revision: Union[str, Sequence[str], None] = 'c2cb1027c58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_user_uid_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_uid_fkey'), 'books', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###
